server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://AUTH-USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[2].id=startup-service
spring.cloud.gateway.routes[2].uri=lb://STARTUP-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/startups/**

spring.cloud.gateway.routes[3].id=investment-service
spring.cloud.gateway.routes[3].uri=lb://INVESTMENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/investments/**

spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/notifications/**

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=false

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
