server.port=8080

spring.application.name=API-GATEWAY

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://AUTH-USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webflux.routes[2].id=startup-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://STARTUP-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/startups/**

spring.cloud.gateway.server.webflux.routes[3].id=investment-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://INVESTMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/investments/**

spring.cloud.gateway.server.webflux.routes[4].id=collaboration-service-teams
spring.cloud.gateway.server.webflux.routes[4].uri=lb://COLLABORATION-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/teams/**

spring.cloud.gateway.server.webflux.routes[5].id=collaboration-service-conversations
spring.cloud.gateway.server.webflux.routes[5].uri=lb://COLLABORATION-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/conversations/**

spring.cloud.gateway.server.webflux.routes[6].id=collaboration-service-messages
spring.cloud.gateway.server.webflux.routes[6].uri=lb://COLLABORATION-SERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/messages/**

spring.cloud.gateway.server.webflux.routes[7].id=notification-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/notifications/**



management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
